# Generated by Django 4.2 on 2024-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=250, unique_for_date="publish"),
        ),
    ]
